name: burst-workers

on:
  workflow_dispatch:
    inputs:
      count:
        description: "Số worker chạy song song"
        required: true
        default: "5"
      minutes:
        description: "Thời gian chạy mỗi worker (phút)"
        required: true
        default: "1"
      parallel:
        description: "Số job chạy cùng lúc"
        required: true
        default: "5"

jobs:
  make-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set.outputs.matrix }}
    steps:
      - id: set
        run: echo "matrix={\"idx\":[1,2,3]}" >> "$GITHUB_OUTPUT"

  run-workers:
    needs: make-matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: ${{ fromJSON(inputs.parallel) }}
      matrix: ${{ fromJSON(needs.make-matrix.outputs.matrix) }}

    steps:
      - run: echo "Worker ${{ matrix.idx }} OK"
