jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build.outputs.matrix }}
      parallel: ${{ steps.build.outputs.parallel }}
      minutes: ${{ steps.build.outputs.minutes }}
    steps:
      - id: build
        shell: bash
        run: |
          COUNT="${{ inputs.count }}"
          PARALLEL="${{ inputs.parallel }}"
          MINUTES="${{ inputs.minutes }}"

          # clamp count [1..100]
          if ! [[ "$COUNT" =~ ^[0-9]+$ ]]; then COUNT=20; fi
          if [ "$COUNT" -lt 1 ]; then COUNT=1; fi
          if [ "$COUNT" -gt 100 ]; then COUNT=100; fi

          # clamp parallel [1..100]
          if ! [[ "$PARALLEL" =~ ^[0-9]+$ ]]; then PARALLEL=20; fi
          if [ "$PARALLEL" -lt 1 ]; then PARALLEL=1; fi
          if [ "$PARALLEL" -gt 100 ]; then PARALLEL=100; fi

          # clamp minutes [1..360]
          if ! [[ "$MINUTES" =~ ^[0-9]+$ ]]; then MINUTES=2; fi
          if [ "$MINUTES" -lt 1 ]; then MINUTES=1; fi
          if [ "$MINUTES" -gt 360 ]; then MINUTES=360; fi

          # build matrix
          LIST=$(seq -s, 1 "$COUNT")
          JSON_MATRIX="{\"worker_id\":[${LIST}]}"
          echo "matrix=$JSON_MATRIX" >> "$GITHUB_OUTPUT"
          echo "parallel=$PARALLEL" >> "$GITHUB_OUTPUT"
          echo "minutes=$MINUTES" >> "$GITHUB_OUTPUT"
