name: Dynamic Workers (safe template)

on:
  workflow_dispatch:
    inputs:
      count:
        description: Number of workers (max 100)
        default: "20"
        required: false
      minutes:
        description: Duration per worker (minutes, 1..360)
        default: "2"
        required: false
      parallel:
        description: Max parallel jobs (1..100)
        default: "20"
        required: false
      payload:
        description: JSON payload for your worker (optional)
        default: "{}"
        required: false

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build.outputs.matrix }}
      parallel: ${{ steps.build.outputs.parallel }}
      minutes: ${{ steps.build.outputs.minutes }}
    steps:
      - id: build
        shell: bash
        run: |
          COUNT="${{ inputs.count }}"
          PARALLEL="${{ inputs.parallel }}"
          MINUTES="${{ inputs.minutes }}"

          # --- sanitize & clamp ---
          # COUNT -> [1..100]
          if ! [[ "$COUNT" =~ ^[0-9]+$ ]]; then COUNT=20; fi
          if [ "$COUNT" -lt 1 ]; then COUNT=1; fi
          if [ "$COUNT" -gt 100 ]; then COUNT=100; fi

          # PARALLEL -> [1..100]
          if ! [[ "$PARALLEL" =~ ^[0-9]+$ ]]; then PARALLEL=20; fi
          if [ "$PARALLEL" -lt 1 ]; then PARALLEL=1; fi
          if [ "$PARALLEL" -gt 100 ]; then PARALLEL=100; fi

          # MINUTES -> [1..360]
          if ! [[ "$MINUTES" =~ ^[0-9]+$ ]]; then MINUTES=2; fi
          if
