name: GitHub Actions Worker
on:
  workflow_dispatch:
    inputs:
      count:
        description: 'Number of workers (max 100)'
        required: true
        default: '50'
      minutes:
        description: 'Run duration in minutes'
        required: true
        default: '2'
      parallel:
        description: 'Number of parallel jobs (max 100)'
        required: true
        default: '50'
      payload:
        description: 'Payload for worker'
        required: true

jobs:
  worker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        worker_id: ${{ fromJSON(format('[{0}]', join(range(1, fromJSON(inputs.count) + 1), ','))) }}
      max-parallel: ${{ fromJSON(inputs.parallel) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyTelegramBotAPI psutil requests

      - name: Download proxy file
        run: |
          echo "Downloading proxy.txt from ${{ secrets.PROXY_SOURCE_URL || 'https://example.com/proxy.txt' }}"
          curl -o proxy.txt ${{ secrets.PROXY_SOURCE_URL || 'https://example.com/proxy.txt' }} || echo "Failed to download proxy.txt, using default"
          ls -l proxy.txt || echo "proxy.txt not found"

      - name: Run worker
        env:
          PAYLOAD: ${{ inputs.payload }}
          WORKER_ID: ${{ matrix.worker_id }}
        run: |
          echo "Running worker $WORKER_ID with payload: $PAYLOAD"
          python vps_worker.py "$PAYLOAD" --worker-id $WORKER_ID
        timeout-minutes: ${{ fromJSON(inputs.minutes) }}
